spring:
  application:
    name:
      lecture-api-server

  datasource:
    url: jdbc:h2:mem:lecture
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
